import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import dashboardRouter from "./dashboard";
import departmentsRouter from "./departments";
import designationsRouter from "./designations";
import employeesRouter from "./employees";
import rolesRouter from "./roles";
import usersRouter from "./users";
import auditLogsRouter from "./audit-logs";
import recruitmentRouter from "./recruitment";
import preOnboardingRouter from "./pre-onboarding";
import employeesExtendedRouter from "./employees-extended";
import onboardingRouter from "./onboarding";
import shiftsRouter from "./shifts";
import attendanceRouter from "./attendance";
import leaveRouter from "./leave";
import permissionsRouter from "./permissions";
import payrollRouter from "./payroll";
import performanceRouter from "./performance";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(dashboardRouter);
router.use(departmentsRouter);
router.use(designationsRouter);
router.use(employeesRouter);
router.use(rolesRouter);
router.use(usersRouter);
router.use(recruitmentRouter);
router.use(preOnboardingRouter);
router.use(employeesExtendedRouter);
router.use(onboardingRouter);
router.use(shiftsRouter);
router.use(attendanceRouter);
router.use(leaveRouter);
router.use(permissionsRouter);
router.use(payrollRouter);
router.use(performanceRouter);
router.use(auditLogsRouter);

export default router;
